name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build first
      run: echo Hello, world!
    - name: Unit Tests
      run: dotnet test    
